[package]
name = "shuttlings-cch23"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
base64 = "0.22.1"
serde = "1.0.216"
serde_json = "1.0.134"
shuttle-axum = "0.49.0"
shuttle-runtime = "0.49.0"
thiserror = "2.0.9"
tokio = "1.28.2"
tower-cookies = "0.10.0"
